version: "3"
services:
  shorten-url-service:
    depends_on:
      - rds
      - redis
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - shorten-url-service-network
    command: [
      "./wait-for-it.sh", "rds:3306", "--",
      "./wait-for-it.sh", "redis:6379", "--",
      "npm", "start"
    ]
    environment:
      - RDS_HOST=rds
      - REDIS_HOST=redis
  rds:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=demo
    volumes:
      - ./localDBInit/:/docker-entrypoint-initdb.d/
    networks:
      - shorten-url-service-network
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
    networks:
      - shorten-url-service-network
networks:
  shorten-url-service-network: