version: "3"
services:
  rds:
    container_name: myapp-rds
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=demo
    volumes:
      - ./localDBInit/:/docker-entrypoint-initdb.d/
  redis:
    container_name: myapp-redis
    image: redis:5.0
    ports:
      - 6379:6379
